services:
  - type: web
    name: linkplease
    runtime: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main_proc
    envVars:
      - key: API_KEY
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: BASE_URL
        value: https://pseudogram-api.onrender.com
      - key: DATABASE_URL
        value: sqlite:///./linkplease.db
